enum class EventType : unsigned char
{
    DEVICE_STATE_CHANGED,
    MOTION_DETECTED,
    MOTION_CLEARED,
    TEMPERATURE_CHANGED,
    DOOR_OPENED,
    DOOR_CLOSED,
    SECURITY_BREACH,
    LOW_BATTERY,
    DEVICE_OFFLINE,
    AUTOMATION_TRIGGERED
};